# Type Name              ID GECOS                        Home                        Shell
g      corvore-ingress   -
u      corvore           -  "CORVORE core runtime"      /var/lib/corvore            /usr/sbin/nologin
u      corvore-collector -  "CORVORE passive collector" /var/lib/corvore-collector  /usr/sbin/nologin
m      corvore-collector corvore-ingress
